apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  replicas: 4
  selector:
    matchLabels:
     app: tomcat
  template:
    metadata:
     labels:
       app: tomcat
    spec:
     imagePullSecrets:
       - name: mydockerhub
     containers:
       - name: tomcat
         image:  cdtsbikaner/tgtomcatapp1:v1
         ports:
          - containerPort: 8080
      
